# Don't print a new line at the start of the prompt
add_newline = false

# Execution duration
[cmd_duration]
min_time = 0
format = "took [$duration](bold yellow)"

# Replace the "❯" symbol in the prompt with "➜"
[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red) "

# Git notifications

